# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: CacheBeta@1
  inputs:
          key: npm | $(Agent.OS) | package-lock.json
          path: /home/vsts/.npm
          restoreKeys: npm | $(Agent.OS) | package-lock.json
  displayName: Cache NPM packages
- task: CacheBeta@1
  inputs:
          key: cypress | $(Agent.OS) | package-lock.json
          path: /home/vsts/.cache/Cypress
          restoreKeys: cypress | $(Agent.OS) | package-lock.json
  displayName: Cache Cypress binary

# Install Node dependencies
- script: |
      npm install
  displayName: 'Install Dependencies'

- script: |
      npx cypress run
  displayName: 'Run Cypress Tests'

- task: PublishTestResults@2
  inputs:
      testResultsFormat: 'JUnit' # Cypress generates JUnit XML reports
      testResultsFiles: '**/test-results.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      failTaskOnFailedTests: true
      mergeTestResults: true
      testRunTitle: 'Cypress Test Run'
  condition: succeededOrFailed()

